### ISSUE TITLE
Store document state in localstorage

### ISSUE THREAD

**Issue by mingard** [dadi/publish#128]
In order to preserve the state of 'draft' documents in post-mvp, we need to replicate the local state value into localstorage. For now, we just need to store the value.

I suggest we use https://github.com/elgerlambert/redux-localstorage but happy if we roll our own.

**Comment by eduardoboucas** [comment]
A couple of questions about this:

1. Do we want to show a warning saying "You have unsaved changes" if the state of the document when the user loads the page comes from a locally-saved version and not the remote API? If so, how would this look visually? Sort of relates to #86.

1. What happens if the remote document has changed since you last opened it, meaning that your local version has potential conflicts with the remote? Do we want to try some form of reconciliation (might be tricky?), or do we simply warn the user and let them make a decision?

**Comment by mingard** [comment]
1. Yes, and that probably means #86 should have a more versatile error message as you suggest
2. That's a good question. We probably don't want to start down this path yet, as it's likely to be fairly complex. Is there anything about this decision that would block you now?

**Comment by eduardoboucas** [comment]
> Yes, and that probably means #86 should have a more versatile error message as you suggest

Indeed. Will discuss on that ticket.

> Is there anything about this decision that would block you now?

Not particularly. I can start with a simple approach of flagging to the user when the remote is out-of-sync and then we can think of a more comprehensive solution (possibly even post-MVP?).

**Comment by mingard** [comment]
@eduardoboucas 
> I can start with a simple approach of flagging to the user when the remote is out-of-sync
Sounds good to me

**Comment by eduardoboucas** [comment]
Closed via #139.
