### ISSUE TITLE
Error when saving user profile

### ISSUE THREAD

**Issue by mingard** [dadi/publish#231]
Although profile saves successfully, a 'wrong credentials' error appears in console

**Comment by eduardoboucas** [comment]
Further to the conversation on Slack, here's what I found on this issue so far.

When saving the user profile, the front-end sends a `PUT` request to the `/session` endpoint, which should be handled [here](https://github.com/dadi/publish/blob/master/app/lib/controllers/session.js#L150). Instead, this method doesn't seem to be called at all, and instead [this one](https://github.com/dadi/publish/blob/master/app/lib/controllers/session.js#L16) is (which should only happen when a user signs in).

Because this method was built to take a password and validate it against a user, hashing it in the process, it does that to the currently available password, which is already hashed. This causes the check to fail and a `401` to be thrown, explaining the issue reported in the ticket.

As pointed out by @mingard, we probably shouldn't even have the hashed password stored in the user store, but that's a separate issue that should probably be captured in another ticket.
