### ISSUE TITLE
Add field description option

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#28]
Optional way of adding a description to a field for less experienced users.

**Comment by jimlambie** [comment]
There is a "comments" property in collection schema fields, I suggest this is what we display in Publish

**Comment by eduardoboucas** [comment]
The idea behind this one is to be able to display field tips, coming from an API field (probably `example`). This would be displayed in the same place as *Required* is currently shown on required fields. When a field is required and has an `example` property, the latter would take precedence.

I've been trying to make field components (e.g. `FieldString`, `FieldReference`, etc.) rely as little as possible on the `schema` prop. For example, the display name used to be read from `schema.displayName` by the components themselves. I have changed this so that a `displayName` prop is passed down to components instead, which gives us more flexibility.

So, for this ticket, I envision a new prop being passed down to components that would determine what text is rendered on the top-right corner (if any). If the field is required, it should receive the string `Required` as the value for that prop.

**Comment by danwdart** [comment]
That's funky, I've always wondered about that - so is it inclusive of "Required" if required? I think it'd be nice if it was.
