### ISSUE TITLE
SSL socket support

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#368]
If you run Publish behind SSL (not using the build in SSL package), the browser sockets need a secure option.

**Comment by mingard** [comment]
You can already do this with: 
```
"publicUrl": {
      "host": "somedomain.tech",
      "port": 443,
      "protocol": "https"
  },
  "server": {
    "host": "0.0.0.0",
    "port": 8080
  }
```

**Comment by abovedave** [comment]
cool, good to know. maybe we should make this match the other products? i.e., in the `server` block?

**Comment by abovedave** [comment]
also, documentation 😄

**Comment by mingard** [comment]
The other apps use same approach, but also include transport security, nothing in the server block:
```json
  "server": {
    "host": "0.0.0.0",
    "port": 80
  },
  "security": {
    "transportSecurity": true
  }
```

The reason `publicUrl` is required instead of just TS is that the access to the server is from the frontend, and needs a publicUrl value. The FE app could probably grab this from location.hostname and have `security.transportSecurity` passed in FE config. It could be used as a switch for WS > WSS. Seems a bit of a convoluted method, so the current method is probably best.

**Comment by abovedave** [comment]
Ok I've added: `publishUrl` and `security.transportSecurity` and all appears good, I see this in the console:

```
sctransport.js?48fe:10 WebSocket connection to 'wss://publish.example.com/socketcluster/' failed: Error during WebSocket handshake: Unexpected response code: 200
```
