### ISSUE TITLE
Document field previews

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#391]
The filename would be useful to start, perhaps also a thumbnail preview, file type icon could be added

<img width="472" alt="screen shot 2018-06-11 at 10 31 19" src="https://user-images.githubusercontent.com/649231/41223786-b1421e3e-6d62-11e8-913f-aee4035700a5.png">

**Comment by danwdart** [comment]
For file type icon, are we going to support a set list?

**Comment by abovedave** [comment]
https://fontawesome.com/ might be a good place to start

**Comment by danwdart** [comment]
Yeah, I use that in my own stuff. What I meant was, should we just support everything in there, and then unknown for not in there, or should we support a subset?

**Comment by anaumovets** [comment]
Hey @abovedave 
icons turned out to be tricky.
Fontawesome doesn't have icons for filetypes, neither do any of these:
https://ionicons.com/ License: MIT
Material Design icons - http://google.github.io/material-design-icons/ License: Apache License Version 2.0
Typicons - http://s-ings.com/typicons/ License: CC BY-SA 3.0
Github Octicons icons - https://octicons.github.com/ License: MIT
Feather - https://feathericons.com/ License: MIT

It's hard to find good looking filetype icons with permissive license. Could you help with that?

**Comment by anaumovets** [comment]
So, just showing thumbnail and filename will do for now. However, we need to ensure that the user can only upload image files in image fields. File resolution can be checked on upload, but how do we inform the user if the file is not an image? Show a dialog box? Is there a standard ui for that? Also, it is not exactly in the scope of this issue, so should I create a separate one?
