### ISSUE TITLE
Editor control of image crops

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#512]
Multiple crops are sometimes required - could we have some sort of 'DADI CDN' aware field subtype?

![imagecrop480](https://user-images.githubusercontent.com/649231/46023386-71d62d80-c0dc-11e8-98fa-2bd166594259.gif)

**Comment by eduardoboucas** [comment]
First of all, it's important to clarify that Publish will not be responsible for any image manipulation operations. The crop control interface will simply generate CDN-compatible URLs based on the crop rectangles drawn by the user (e.g. `?resizeStyle=crop&crop=10,15,200,300`).

Secondly, it's worth revisiting how Publish and API handle media. Files are uploaded to an API media bucket, which are shown by Publish as the Media Library (`/media` URL). Media files can then be used in any document using a `Media` field (or a `Reference` field, for legacy reasons). In practice, this means adding the ID of a media item to a field in a document.

In my opinion, items in the media library should be the raw, original assets and therefore not affected by transformations applied by the user. Instead, these transformations (such as cropping) should happen on the  **references** to those assets. In practice, this means that the image of the basketball player shown above could be uploaded once to the media library, and then be used in different documents of different collections and cropped in different ways in each of those contexts.

I see two ways/workflows in which image cropping would be useful:

## 1. Inline images in rich editor

This is the simplest use case. When adding an inline image to a Markdown field, the user should be able to select a crop. Since all we're doing here is adding an image URL to the field's contents, we would simply need to append the CDN crop coordinates to the end of the URL.

## 2. Pre-defined image crops

A field of type `Media` could have any number of pre-defined crops defined, as part of the `publish` block. For example, imagine a field called `mainImage` in an `articles` collection, with four crops defined: Master Crop, Small Square, Large Horizontal and Medium 2:2 (as per the image above), each with their dimension/ratio constraints.

When selecting an image for the given field, the user would be asked to select a crop for each of the pre-defined slots. The resulting coordinates would be saved alongside the ID of the media asset in the `Media` field:

```json
{
  "title": "An article about basketball",
  "mainImage": {
    "_id": "58576e72bafa53b625aebd4f",
    "caption": "Two dudes playing basketball",
    "crops": {
      "mainCrop": [16, 32, 64, 128],
      "smallSquare": [32, 64, 64, 128],
      "largeHorizontal": [64, 128, 256, 512],
      "medium22": [128, 256, 512, 1024]
    }
  }
}
```

/cc @josephdenne
