### ISSUE TITLE
Markdown formatted fields do not respect multiline: true

### ISSUE THREAD

**Issue by josephdenne** [dadi/publish#703]
### Expected behavior

That fields of `"format": "markdown",` with `"multiline": true,` will be sized accordingly in the document interface.

### Actual behavior

`"multiline": true,` has no effect.

<img width="1551" alt="Screenshot 2019-04-21 at 13 20 10" src="https://user-images.githubusercontent.com/150408/56469977-737c8f80-6438-11e9-8f11-c143ed78a276.png">

### Steps to reproduce the problem

Add a field of type Sting to a collection with `"format": "markdown",` and `"multiline": true,`. For example:

```
    "body": {
      "type": "String",
      "required": true,
      "label": "Body",
      "format": "markdown",
      "publish": {
        "placement": "main",
        "display": {
          "edit": true,
          "list": false
        },
        "multiline": true,
        "resizable": true
      }
    },
```

**Comment by eduardoboucas** [comment]
By default, a `String` field generates an `<input>` element, which supports a single line of text. To allow multiple lines, we introduced the `multiline` property which generates a `<textarea>` instead.

This is a non-issue when `"format": "markdown"` however, because it uses the rich editor component which natively supports multiple lines. In your screenshot above, you'll see that _Body_ will expand in size as you add more lines of text.

Are you referring to the default size of the field, saying it should be larger because of the `multiline` property?
